name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  # If the event is type of "push"
  PUSH_EVENT: ${{ github.event_name == 'push' }}

  # Whether to skip the tagging
  SKIP_TAG: ${{ !contains(join(fromJson(toJson(github.event.commits)), ' '), '[skip-tag]') }}

jobs:
  validate:
    name: Run lint and unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # Only deploy on push events
      - if: ${{ env.PUSH_EVENT == 'true' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Skip if the commit message contains '[skip-tag]'
      # Otherwise, only run on push events
      - if: ${{ env.SKIP_TAG == 'false' && env.PUSH_EVENT == 'true' }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  # This job will run only if the deployment job fails
  notify-failure:
    name: Notify on deployment failure
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Send a Discord notification
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚨 Deployment failed!"

  # This job will run only if the deployment job succeeds
  notify-success:
    name: Notify on successful deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Send a Discord notification
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "✅ Deployment succeeded!"
